import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/layouts/navbar'
import Footer from '../components/layouts/footer'
import Layouts from '../components/layouts/layouts'
import Links from '../components/links'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Music-site</title>
        <meta name="description" content="Generated by Music-site" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar/>
      <main className="">
        
        <Layouts/>
        <Links/>
      </main>
        <Footer/>

    </div>
  )
}
